FROM golang:1.21-alpine

WORKDIR /app

# Initialize the module and get dependencies inside the container
RUN go mod init go-engine && \
    go get github.com/gin-gonic/gin && \
    go get github.com/prometheus/client_golang/prometheus && \
    go get github.com/prometheus/client_golang/prometheus/promhttp

COPY . .

# Build the Go application
RUN go build -o main .

EXPOSE 3001

CMD ["./main"]